In [1]:
import torch
import torch.nn as nn
from torchmetrics.classification import BinaryJaccardIndex, JaccardIndex
from torchmetrics.functional.classification import multiclass_jaccard_index
from torchmetrics.functional.segmentation import mean_iou
from torch.nn.functional import softmax, one_hot

In [2]:
X = torch.rand(size=(1,3,3,8))
Y = (torch.rand(size=(1,3,3,8)) > 0.5) * 1

In [3]:
print(X)
print(Y)

tensor([[[[0.0358, 0.2173, 0.2538, 0.7108, 0.8230, 0.2559, 0.7701, 0.3125],
          [0.2402, 0.7119, 0.0858, 0.1669, 0.4924, 0.0781, 0.5905, 0.1053],
          [0.4365, 0.3281, 0.6662, 0.3233, 0.9261, 0.5585, 0.4900, 0.8492]],

         [[0.2486, 0.2673, 0.9019, 0.3212, 0.0175, 0.6288, 0.4707, 0.5165],
          [0.3340, 0.0512, 0.0904, 0.7970, 0.1480, 0.9273, 0.3946, 0.1251],
          [0.4251, 0.8253, 0.9633, 0.3509, 0.9121, 0.6794, 0.8785, 0.0808]],

         [[0.0695, 0.8253, 0.1397, 0.9885, 0.4432, 0.3010, 0.2497, 0.8386],
          [0.4003, 0.8970, 0.0274, 0.9861, 0.8062, 0.7423, 0.2016, 0.7116],
          [0.9766, 0.9395, 0.2177, 0.2652, 0.8135, 0.3008, 0.6514, 0.5615]]]])
tensor([[[[1, 1, 0, 1, 0, 0, 0, 1],
          [0, 1, 0, 0, 1, 1, 0, 1],
          [0, 0, 0, 1, 0, 0, 0, 1]],

         [[0, 0, 1, 0, 0, 0, 1, 0],
          [0, 1, 0, 1, 0, 0, 1, 1],
          [0, 1, 0, 1, 0, 0, 1, 1]],

         [[0, 0, 0, 1, 1, 1, 1, 0],
          [1, 1, 1, 0, 1, 0, 0, 0],
          [0, 0, 

In [4]:
m1 = BinaryJaccardIndex()
m2 = JaccardIndex(task='binary', average='micro')

In [5]:
print(m1(X,Y), m2(X,Y))

tensor(0.2157) tensor(0.2157)


In [6]:
# s = 0
# for i in range(7):
#     t = m1(X[i], Y[i])
#     s += t
#     print(t)
# print(s, s/8)

In [7]:
p1 = torch.mean(X, axis = (1,2))
print(p1)

tensor([[0.3518, 0.5626, 0.3718, 0.5456, 0.5980, 0.4969, 0.5219, 0.4557]])


In [8]:
print(torch.mean(X[0]))

tensor(0.4880)


In [9]:
# print(torch.mean(X[1]))

## Torchmetrics multiclass_jaccard_index vs mean_iou

In [10]:
pred = softmax(torch.rand((4,21,224,224)), dim=1)
target = torch.randint(21, (4,224,224))
target_oh = torch.permute(one_hot(target, num_classes = 21), (0,3,1,2))
pred_oh = torch.permute(one_hot(torch.argmax(pred, dim=1), num_classes = 21), (0,3,1,2))

In [11]:
mIU = mean_iou(torch.argmax(pred, dim=1), target, num_classes=21, per_class=True)
mIU1 = mean_iou(pred_oh, target_oh, num_classes=21, per_class=True)
iou = multiclass_jaccard_index(pred, target, num_classes = 21, average = None)
iou2 = multiclass_jaccard_index(pred, target, num_classes = 21)

In [19]:
print('mIU', mIU)
# print('iou', iou)
# print('iou2', iou2)
print('mIU1', mIU1)

mIU tensor([[0.0233, 0.0272, 0.0243, 0.0265, 0.0255, 0.0281, 0.0250, 0.0246, 0.0226,
         0.0290, 0.0270, 0.0217, 0.0268, 0.0241, 0.0230, 0.0248, 0.0189, 0.0248,
         0.0241, 0.0242, 0.0258],
        [0.0252, 0.0244, 0.0231, 0.0276, 0.0241, 0.0264, 0.0253, 0.0239, 0.0226,
         0.0230, 0.0272, 0.0268, 0.0262, 0.0277, 0.0251, 0.0271, 0.0239, 0.0244,
         0.0249, 0.0285, 0.0277],
        [0.0238, 0.0247, 0.0253, 0.0191, 0.0265, 0.0245, 0.0263, 0.0228, 0.0197,
         0.0261, 0.0247, 0.0198, 0.0239, 0.0280, 0.0237, 0.0221, 0.0212, 0.0249,
         0.0248, 0.0253, 0.0278],
        [0.0226, 0.0276, 0.0243, 0.0273, 0.0211, 0.0277, 0.0235, 0.0260, 0.0266,
         0.0256, 0.0220, 0.0264, 0.0274, 0.0228, 0.0250, 0.0272, 0.0231, 0.0234,
         0.0260, 0.0211, 0.0214]])
mIU1 tensor([[0.0233, 0.0272, 0.0243, 0.0265, 0.0255, 0.0281, 0.0250, 0.0246, 0.0226,
         0.0290, 0.0270, 0.0217, 0.0268, 0.0241, 0.0230, 0.0248, 0.0189, 0.0248,
         0.0241, 0.0242, 0.0258],
        [0

In [13]:
torch.mean(mIU, dim=0)

tensor([0.0237, 0.0260, 0.0243, 0.0251, 0.0243, 0.0267, 0.0250, 0.0244, 0.0229,
        0.0259, 0.0252, 0.0237, 0.0261, 0.0256, 0.0242, 0.0253, 0.0218, 0.0244,
        0.0250, 0.0248, 0.0257])

In [14]:
# x = torch.zeros([21])
# print(x.shape)
# for i in range(21):
#     x[i] = torch.sum(torch.where(target == i, 1, 0))
#     print(x[i])
# print(torch.sum(x))

In [15]:
4*224*224

200704

In [16]:
nc = 5
preds = torch.randint(0, 2, (4, nc, 16, 16))  # 4 samples, 5 classes, 16x16 prediction
target = torch.randint(0, 2, (4, nc, 16, 16))  # 4 samples, 5 classes, 16x16 target
print(mean_iou(preds, target, num_classes=nc))

print(mean_iou(preds, target, num_classes=nc, per_class=True))

tensor([0.3384, 0.3441, 0.3440, 0.3681])
tensor([[0.3299, 0.3430, 0.3316, 0.3388, 0.3487],
        [0.3515, 0.3660, 0.3299, 0.3216, 0.3514],
        [0.4065, 0.3194, 0.3452, 0.2900, 0.3590],
        [0.3618, 0.3594, 0.3750, 0.4127, 0.3315]])


In [17]:
print(mean_iou(torch.argmax(preds, dim=1), torch.argmax(target, dim=1), num_classes=nc))

print(mean_iou(torch.argmax(preds, dim=1), torch.argmax(target, dim=1), num_classes=nc, per_class=True))

tensor([0.1040, 0.1081, 0.1263, 0.1366])
tensor([[0.3515, 0.1473, 0.0213, 0.0000, 0.0000],
        [0.3689, 0.1161, 0.0556, 0.0000, 0.0000],
        [0.4208, 0.1538, 0.0566, 0.0000, 0.0000],
        [0.3768, 0.1316, 0.0877, 0.0870, 0.0000]])


In [18]:
multiclass_jaccard_index(preds, target, num_classes = 5, average = None)

tensor([0.3262, 0.3488, 0.0000, 0.0000, 0.0000])

In [20]:
x = list(range(2,4))

In [21]:
x

[2, 3]