In [1]:
import torch
import torch.nn as nn
from torchmetrics.classification import BinaryJaccardIndex, JaccardIndex
from torchmetrics.functional.classification import multiclass_jaccard_index
from torchmetrics.functional.segmentation import mean_iou
from torch.nn.functional import softmax

In [2]:
X = torch.rand(size=(1,3,3,8))
Y = (torch.rand(size=(1,3,3,8)) > 0.5) * 1

In [3]:
print(X)
print(Y)

tensor([[[[0.4601, 0.1919, 0.4797, 0.6342, 0.5504, 0.2742, 0.6939, 0.7327],
          [0.8533, 0.9580, 0.3367, 0.3670, 0.8418, 0.8216, 0.8692, 0.6259],
          [0.2428, 0.3988, 0.6043, 0.5449, 0.5952, 0.9231, 0.6350, 0.9169]],

         [[0.5501, 0.2337, 0.6374, 0.0183, 0.0408, 0.0028, 0.7865, 0.1236],
          [0.0787, 0.3616, 0.4307, 0.7634, 0.0714, 0.7266, 0.4818, 0.3873],
          [0.1183, 0.9694, 0.6614, 0.7282, 0.5056, 0.7907, 0.8138, 0.9914]],

         [[0.5383, 0.9685, 0.5780, 0.7880, 0.4017, 0.7815, 0.5387, 0.5998],
          [0.6881, 0.4335, 0.9212, 0.6694, 0.6358, 0.9816, 0.5827, 0.1091],
          [0.5707, 0.8252, 0.6872, 0.4957, 0.0910, 0.8257, 0.7007, 0.1504]]]])
tensor([[[[1, 1, 0, 1, 0, 0, 1, 1],
          [0, 0, 0, 1, 0, 1, 0, 1],
          [1, 1, 0, 1, 0, 0, 0, 0]],

         [[1, 1, 1, 1, 1, 0, 0, 1],
          [0, 1, 0, 1, 1, 0, 0, 0],
          [0, 0, 0, 0, 1, 0, 0, 1]],

         [[1, 0, 1, 0, 0, 1, 0, 1],
          [0, 0, 0, 0, 1, 1, 1, 1],
          [0, 0, 

In [4]:
m1 = BinaryJaccardIndex()
m2 = JaccardIndex(task='binary', average='micro')

In [5]:
print(m1(X,Y), m2(X,Y))

tensor(0.3390) tensor(0.3390)


In [6]:
# s = 0
# for i in range(7):
#     t = m1(X[i], Y[i])
#     s += t
#     print(t)
# print(s, s/8)

In [7]:
p1 = torch.mean(X, axis = (1,2))
print(p1)

tensor([[0.4556, 0.5934, 0.5930, 0.5566, 0.4149, 0.6809, 0.6780, 0.5152]])


In [8]:
print(torch.mean(X[0]))

tensor(0.5609)


In [9]:
# print(torch.mean(X[1]))

## Torchmetrics multiclass_jaccard_index vs mean_iou

In [10]:
pred = softmax(torch.rand((4,21,224,224)), dim=1)
target = torch.randint(21, (4,224,224))

In [11]:
mIU = mean_iou(torch.argmax(pred, dim=1), target, num_classes=21, per_class=True)
iou = multiclass_jaccard_index(pred, target, num_classes = 21, average = None)
iou2 = multiclass_jaccard_index(pred, target, num_classes = 21)

In [12]:
print('mIU', mIU)
print('iou', iou)
print('iou2', iou2)

mIU tensor([[0.0239, 0.0234, 0.0242, 0.0264, 0.0248, 0.0266, 0.0239, 0.0252, 0.0189,
         0.0211, 0.0234, 0.0275, 0.0274, 0.0229, 0.0248, 0.0263, 0.0211, 0.0252,
         0.0225, 0.0219, 0.0217],
        [0.0213, 0.0185, 0.0276, 0.0235, 0.0272, 0.0208, 0.0248, 0.0249, 0.0247,
         0.0211, 0.0238, 0.0248, 0.0255, 0.0233, 0.0249, 0.0241, 0.0238, 0.0246,
         0.0243, 0.0249, 0.0226],
        [0.0234, 0.0241, 0.0212, 0.0266, 0.0220, 0.0273, 0.0257, 0.0248, 0.0246,
         0.0249, 0.0226, 0.0231, 0.0277, 0.0226, 0.0278, 0.0253, 0.0233, 0.0230,
         0.0248, 0.0242, 0.0248],
        [0.0254, 0.0241, 0.0258, 0.0210, 0.0228, 0.0235, 0.0235, 0.0213, 0.0208,
         0.0215, 0.0286, 0.0223, 0.0202, 0.0200, 0.0249, 0.0224, 0.0211, 0.0274,
         0.0232, 0.0228, 0.0244]])
iou tensor([0.0235, 0.0226, 0.0247, 0.0244, 0.0242, 0.0245, 0.0245, 0.0240, 0.0222,
        0.0221, 0.0246, 0.0244, 0.0252, 0.0222, 0.0256, 0.0246, 0.0224, 0.0251,
        0.0237, 0.0234, 0.0234])
iou2 tensor(0.

In [13]:
torch.mean(mIU, dim=0)

tensor([0.0235, 0.0225, 0.0247, 0.0244, 0.0242, 0.0245, 0.0245, 0.0240, 0.0223,
        0.0222, 0.0246, 0.0244, 0.0252, 0.0222, 0.0256, 0.0245, 0.0223, 0.0251,
        0.0237, 0.0234, 0.0234])

In [14]:
torch.sum(torch.where(target == 0, 1, 0))

tensor(9561)