In [1]:
import torch
import torch.nn as nn
from torchmetrics.classification import BinaryJaccardIndex, JaccardIndex
from torchmetrics.functional.classification import multiclass_jaccard_index
from torchmetrics.functional.segmentation import mean_iou
from torch.nn.functional import softmax, one_hot

In [2]:
X = torch.rand(size=(1,3,3,8))
Y = (torch.rand(size=(1,3,3,8)) > 0.5) * 1

In [3]:
print(X)
print(Y)

tensor([[[[0.9979, 0.9064, 0.6214, 0.5084, 0.0336, 0.6068, 0.3358, 0.7130],
          [0.7174, 0.9875, 0.2235, 0.1863, 0.2172, 0.2694, 0.1721, 0.1390],
          [0.0573, 0.5182, 0.9905, 0.2724, 0.5684, 0.2290, 0.9102, 0.3449]],

         [[0.6205, 0.1875, 0.0445, 0.4691, 0.5192, 0.6323, 0.1046, 0.3674],
          [0.6882, 0.7167, 0.8168, 0.2266, 0.3215, 0.9777, 0.5965, 0.2912],
          [0.9362, 0.5998, 0.9733, 0.5457, 0.5049, 0.4693, 0.8804, 0.2490]],

         [[0.7213, 0.1479, 0.3675, 0.2404, 0.0701, 0.5508, 0.0919, 0.6208],
          [0.2228, 0.4111, 0.4284, 0.7808, 0.7925, 0.5914, 0.3325, 0.4821],
          [0.5674, 0.8845, 0.4381, 0.9186, 0.0574, 0.1556, 0.8491, 0.8704]]]])
tensor([[[[1, 0, 0, 1, 1, 0, 0, 1],
          [0, 0, 0, 0, 0, 1, 0, 0],
          [0, 1, 0, 1, 1, 1, 0, 1]],

         [[0, 1, 0, 0, 1, 0, 1, 1],
          [0, 0, 0, 1, 1, 0, 1, 0],
          [1, 0, 1, 0, 0, 1, 1, 0]],

         [[1, 0, 0, 0, 0, 1, 1, 1],
          [1, 1, 0, 0, 0, 1, 1, 0],
          [1, 1, 

In [4]:
m1 = BinaryJaccardIndex()
m2 = JaccardIndex(task='binary', average='micro')

In [5]:
print(m1(X,Y), m2(X,Y))

tensor(0.2963) tensor(0.2963)


In [6]:
# s = 0
# for i in range(7):
#     t = m1(X[i], Y[i])
#     s += t
#     print(t)
# print(s, s/8)

In [7]:
p1 = torch.mean(X, axis = (1,2))
print(p1)

tensor([[0.6143, 0.5955, 0.5449, 0.4609, 0.3427, 0.4980, 0.4748, 0.4531]])


In [8]:
print(torch.mean(X[0]))

tensor(0.4980)


In [9]:
# print(torch.mean(X[1]))

## Torchmetrics multiclass_jaccard_index vs mean_iou

In [10]:
pred = softmax(torch.rand((4,21,224,224)), dim=1)
target = torch.randint(21, (4,224,224))
target_oh = torch.permute(one_hot(target, num_classes = 21), (0,3,1,2))
pred_oh = torch.permute(one_hot(torch.argmax(pred, dim=1), num_classes = 21), (0,3,1,2))

In [11]:
mIU = mean_iou(torch.argmax(pred, dim=1), target, num_classes=21, per_class=True)
mIU1 = mean_iou(pred_oh, target_oh, num_classes=21, per_class=True)
iou = multiclass_jaccard_index(pred, target, num_classes = 21, average = None)
iou2 = multiclass_jaccard_index(pred, target, num_classes = 21)

In [12]:
print('mIU', mIU)
print('mIU1', mIU1)
print('iou', iou)
print('iou2', iou2)

mIU tensor([[0.0208, 0.0192, 0.0234, 0.0231, 0.0268, 0.0269, 0.0206, 0.0251, 0.0257,
         0.0236, 0.0223, 0.0213, 0.0245, 0.0195, 0.0241, 0.0208, 0.0244, 0.0247,
         0.0247, 0.0263, 0.0232],
        [0.0222, 0.0219, 0.0259, 0.0265, 0.0295, 0.0228, 0.0250, 0.0244, 0.0237,
         0.0239, 0.0244, 0.0259, 0.0241, 0.0242, 0.0247, 0.0261, 0.0278, 0.0228,
         0.0223, 0.0247, 0.0252],
        [0.0255, 0.0253, 0.0221, 0.0218, 0.0228, 0.0231, 0.0232, 0.0244, 0.0228,
         0.0230, 0.0248, 0.0241, 0.0200, 0.0264, 0.0257, 0.0266, 0.0264, 0.0279,
         0.0245, 0.0275, 0.0249],
        [0.0271, 0.0248, 0.0223, 0.0232, 0.0227, 0.0232, 0.0243, 0.0258, 0.0265,
         0.0236, 0.0245, 0.0225, 0.0221, 0.0281, 0.0238, 0.0223, 0.0247, 0.0234,
         0.0258, 0.0265, 0.0255]])
mIU1 tensor([[0.0208, 0.0192, 0.0234, 0.0231, 0.0268, 0.0269, 0.0206, 0.0251, 0.0257,
         0.0236, 0.0223, 0.0213, 0.0245, 0.0195, 0.0241, 0.0208, 0.0244, 0.0247,
         0.0247, 0.0263, 0.0232],
        [0

In [13]:
torch.mean(mIU, dim=0)

tensor([0.0239, 0.0228, 0.0234, 0.0236, 0.0254, 0.0240, 0.0233, 0.0250, 0.0247,
        0.0235, 0.0240, 0.0235, 0.0227, 0.0246, 0.0246, 0.0239, 0.0258, 0.0247,
        0.0243, 0.0263, 0.0247])

In [14]:
# x = torch.zeros([21])
# print(x.shape)
# for i in range(21):
#     x[i] = torch.sum(torch.where(target == i, 1, 0))
#     print(x[i])
# print(torch.sum(x))

In [15]:
4*224*224

200704

In [16]:
nc = 5
preds = torch.randint(0, 2, (4, nc, 16, 16))  # 4 samples, 5 classes, 16x16 prediction
target = torch.randint(0, 2, (4, nc, 16, 16))  # 4 samples, 5 classes, 16x16 target
print(mean_iou(preds, target, num_classes=nc))

print(mean_iou(preds, target, num_classes=nc, per_class=True))

tensor([0.3670, 0.3325, 0.3431, 0.3164])
tensor([[0.3103, 0.3757, 0.4138, 0.3791, 0.3560],
        [0.3053, 0.3279, 0.3247, 0.3575, 0.3472],
        [0.3608, 0.3462, 0.3065, 0.3770, 0.3250],
        [0.3077, 0.3284, 0.3021, 0.3300, 0.3138]])


In [17]:
print(mean_iou(torch.argmax(preds, dim=1), torch.argmax(target, dim=1), num_classes=nc))

print(mean_iou(torch.argmax(preds, dim=1), torch.argmax(target, dim=1), num_classes=nc, per_class=True))

tensor([0.1341, 0.1214, 0.1331, 0.1132])
tensor([[0.3478, 0.1920, 0.0435, 0.0870, 0.0000],
        [0.3385, 0.0982, 0.1455, 0.0250, 0.0000],
        [0.4000, 0.1596, 0.0545, 0.0513, 0.0000],
        [0.3177, 0.1405, 0.0455, 0.0625, 0.0000]])


In [18]:
multiclass_jaccard_index(preds, target, num_classes = 5, average = None)

tensor([0.3416, 0.3401, 0.0000, 0.0000, 0.0000])

In [19]:
x = list(range(2,4))

In [20]:
pred = torch.randint(5, (4,64,64))
target = torch.randint(5, (4,64,64))
target_oh = torch.permute(one_hot(target, num_classes = 5), (0,3,1,2))
pred_oh = torch.permute(one_hot(pred, num_classes = 5), (0,3,1,2))

In [21]:
mIU = mean_iou(pred, target, num_classes=5, per_class=True)
mIU1 = mean_iou(pred_oh, target_oh, num_classes=5, per_class=True)
iou = multiclass_jaccard_index(pred, target, num_classes = 5, average = None)
iou2 = multiclass_jaccard_index(pred, target, num_classes = 5)

In [22]:
# print('mIU', mIU)
print('Mean mIU', torch.mean(mIU, dim=0))
# print('mIU1', mIU1)
print('Mean mIU1', torch.mean(mIU1, dim=0))
print('iou', iou)
print('iou2', iou2)

Mean mIU tensor([0.1051, 0.1068, 0.1020, 0.1108, 0.1121])
Mean mIU1 tensor([0.1051, 0.1068, 0.1020, 0.1108, 0.1121])
iou tensor([0.1051, 0.1068, 0.1020, 0.1107, 0.1121])
iou2 tensor(0.1074)
