In [1]:
import torch
import torch.nn as nn
from torchmetrics.classification import BinaryJaccardIndex, JaccardIndex
from torchmetrics.functional.classification import multiclass_jaccard_index
from torchmetrics.functional.segmentation import mean_iou
from torch.nn.functional import softmax

In [2]:
X = torch.rand(size=(1,3,3,8))
Y = (torch.rand(size=(1,3,3,8)) > 0.5) * 1

In [3]:
print(X)
print(Y)

tensor([[[[0.7495, 0.2836, 0.5981, 0.0999, 0.3646, 0.7150, 0.0904, 0.0492],
          [0.7001, 0.0543, 0.1513, 0.3137, 0.0512, 0.4296, 0.4712, 0.5824],
          [0.6848, 0.8028, 0.0579, 0.1653, 0.7092, 0.1439, 0.5257, 0.1387]],

         [[0.1029, 0.7284, 0.8222, 0.7077, 0.8884, 0.8488, 0.4832, 0.3017],
          [0.9407, 0.6712, 0.7788, 0.4797, 0.3490, 0.1804, 0.3083, 0.2600],
          [0.8882, 0.7541, 0.0122, 0.1689, 0.0690, 0.1365, 0.3821, 0.3262]],

         [[0.6227, 0.6985, 0.7226, 0.0286, 0.7785, 0.6104, 0.3292, 0.4595],
          [0.6830, 0.4235, 0.1248, 0.0018, 0.7461, 0.2171, 0.6366, 0.2748],
          [0.3904, 0.7253, 0.3386, 0.5720, 0.5836, 0.7187, 0.8810, 0.1597]]]])
tensor([[[[0, 1, 0, 0, 1, 1, 0, 0],
          [0, 0, 1, 0, 0, 1, 1, 0],
          [1, 1, 0, 1, 1, 0, 0, 1]],

         [[0, 1, 0, 0, 0, 1, 0, 1],
          [1, 1, 0, 0, 0, 0, 0, 1],
          [1, 1, 1, 0, 1, 1, 0, 1]],

         [[0, 1, 1, 0, 0, 1, 0, 1],
          [0, 1, 1, 0, 1, 1, 0, 0],
          [1, 1, 

In [4]:
m1 = BinaryJaccardIndex()
m2 = JaccardIndex(task='binary', average='micro')

In [5]:
print(m1(X,Y), m2(X,Y))

tensor(0.3333) tensor(0.3333)


In [6]:
# s = 0
# for i in range(7):
#     t = m1(X[i], Y[i])
#     s += t
#     print(t)
# print(s, s/8)

In [7]:
p1 = torch.mean(X, axis = (1,2))
print(p1)

tensor([[0.6403, 0.5713, 0.4007, 0.2819, 0.5044, 0.4445, 0.4564, 0.2836]])


In [8]:
print(torch.mean(X[0]))

tensor(0.4479)


In [9]:
# print(torch.mean(X[1]))

## Torchmetrics multiclass_jaccard_index vs mean_iou

In [10]:
pred = softmax(torch.rand((4,21,224,224)), dim=1)
target = torch.randint(21, (4,224,224))

In [11]:
mIU = mean_iou(torch.argmax(pred, dim=1), target, num_classes=21, per_class=True)
iou = multiclass_jaccard_index(pred, target, num_classes = 21, average = None)
iou2 = multiclass_jaccard_index(pred, target, num_classes = 21)

In [12]:
print('mIU', mIU)
print('iou', iou)
print('iou2', iou2)

mIU tensor([[0.0221, 0.0227, 0.0234, 0.0283, 0.0256, 0.0224, 0.0245, 0.0204, 0.0218,
         0.0266, 0.0224, 0.0278, 0.0223, 0.0298, 0.0286, 0.0235, 0.0244, 0.0272,
         0.0216, 0.0254, 0.0248],
        [0.0221, 0.0263, 0.0235, 0.0230, 0.0246, 0.0224, 0.0271, 0.0270, 0.0249,
         0.0225, 0.0271, 0.0261, 0.0247, 0.0209, 0.0233, 0.0240, 0.0242, 0.0247,
         0.0270, 0.0226, 0.0245],
        [0.0218, 0.0240, 0.0288, 0.0243, 0.0249, 0.0238, 0.0264, 0.0283, 0.0285,
         0.0233, 0.0253, 0.0272, 0.0259, 0.0260, 0.0261, 0.0269, 0.0228, 0.0220,
         0.0246, 0.0219, 0.0228],
        [0.0246, 0.0214, 0.0231, 0.0264, 0.0212, 0.0274, 0.0230, 0.0249, 0.0253,
         0.0231, 0.0220, 0.0217, 0.0248, 0.0231, 0.0210, 0.0224, 0.0234, 0.0264,
         0.0242, 0.0275, 0.0266]])
iou tensor([0.0226, 0.0236, 0.0247, 0.0255, 0.0241, 0.0240, 0.0253, 0.0251, 0.0252,
        0.0238, 0.0241, 0.0257, 0.0244, 0.0250, 0.0247, 0.0242, 0.0237, 0.0250,
        0.0243, 0.0244, 0.0247])
iou2 tensor(0.

In [13]:
torch.mean(mIU, dim=0)

tensor([0.0226, 0.0236, 0.0247, 0.0255, 0.0241, 0.0240, 0.0252, 0.0252, 0.0251,
        0.0239, 0.0242, 0.0257, 0.0244, 0.0249, 0.0247, 0.0242, 0.0237, 0.0251,
        0.0243, 0.0244, 0.0247])

In [14]:
torch.sum(torch.where(target == 0, 1, 0))

tensor(9409)