In [1]:
import torch
import torch.nn as nn
from torchmetrics.classification import BinaryJaccardIndex, JaccardIndex

In [2]:
X = torch.rand(size=(1,3,3,8))
Y = (torch.rand(size=(1,3,3,8)) > 0.5) * 1

In [3]:
print(X)
print(Y)

tensor([[[[0.6274, 0.0225, 0.8790, 0.9950, 0.2034, 0.1134, 0.5777, 0.5050],
          [0.4781, 0.3134, 0.6852, 0.6214, 0.0401, 0.9174, 0.1897, 0.2352],
          [0.4800, 0.4560, 0.5523, 0.8078, 0.7045, 0.2192, 0.0171, 0.2149]],

         [[0.0323, 0.8328, 0.1422, 0.7570, 0.2224, 0.1570, 0.2796, 0.7968],
          [0.9745, 0.3978, 0.4186, 0.9271, 0.5507, 0.7015, 0.9941, 0.2093],
          [0.6826, 0.6648, 0.4675, 0.0211, 0.1149, 0.6199, 0.7752, 0.4012]],

         [[0.7374, 0.0381, 0.3704, 0.1497, 0.4685, 0.5419, 0.2210, 0.3646],
          [0.4339, 0.7055, 0.5920, 0.6108, 0.0092, 0.2258, 0.2301, 0.9766],
          [0.7831, 0.5795, 0.8297, 0.1207, 0.5731, 0.2802, 0.5636, 0.3783]]]])
tensor([[[[1, 1, 0, 0, 0, 0, 0, 1],
          [0, 1, 0, 1, 1, 1, 1, 1],
          [1, 0, 1, 1, 0, 0, 0, 1]],

         [[1, 1, 0, 1, 1, 1, 0, 1],
          [0, 0, 1, 1, 1, 0, 0, 1],
          [1, 1, 0, 1, 1, 0, 0, 0]],

         [[1, 0, 0, 0, 0, 1, 0, 1],
          [0, 0, 0, 1, 0, 1, 1, 1],
          [1, 0, 

In [4]:
m1 = BinaryJaccardIndex()
m2 = JaccardIndex(task='binary', average='micro')

In [5]:
print(m1(X,Y), m2(X,Y))

tensor(0.3396) tensor(0.3396)


In [6]:
s = 0
for i in range(7):
    t = m1(X[i], Y[i])
    s += t
    print(t)
print(s, s/8)

tensor(0.3396)


IndexError: index 1 is out of bounds for dimension 0 with size 1

In [7]:
p1 = torch.mean(X, axis = (1,2))
print(p1)

tensor([[0.5810, 0.4456, 0.5486, 0.5567, 0.3207, 0.4196, 0.4276, 0.4535]])


In [8]:
print(torch.mean(X[0]))

tensor(0.4692)


In [9]:
print(torch.mean(X[1]))

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [10]:
X[0]

tensor([[[0.6274, 0.0225, 0.8790, 0.9950, 0.2034, 0.1134, 0.5777, 0.5050],
         [0.4781, 0.3134, 0.6852, 0.6214, 0.0401, 0.9174, 0.1897, 0.2352],
         [0.4800, 0.4560, 0.5523, 0.8078, 0.7045, 0.2192, 0.0171, 0.2149]],

        [[0.0323, 0.8328, 0.1422, 0.7570, 0.2224, 0.1570, 0.2796, 0.7968],
         [0.9745, 0.3978, 0.4186, 0.9271, 0.5507, 0.7015, 0.9941, 0.2093],
         [0.6826, 0.6648, 0.4675, 0.0211, 0.1149, 0.6199, 0.7752, 0.4012]],

        [[0.7374, 0.0381, 0.3704, 0.1497, 0.4685, 0.5419, 0.2210, 0.3646],
         [0.4339, 0.7055, 0.5920, 0.6108, 0.0092, 0.2258, 0.2301, 0.9766],
         [0.7831, 0.5795, 0.8297, 0.1207, 0.5731, 0.2802, 0.5636, 0.3783]]])

In [11]:
rv = torch.rand(size=(2,))
print(rv)

tensor([0.9810, 0.9710])


In [12]:
loss = nn.L1Loss(reduction='sum')

In [13]:
loss(p1, rv)

/home/omkar/miniconda3/envs/unet/lib/python3.10/site-packages/torch/nn/modules/loss.py:101: UserWarning: Using a target size (torch.Size([2])) that is different to the input size (torch.Size([1, 8])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(input, target, reduction=self.reduction)


RuntimeError: The size of tensor a (8) must match the size of tensor b (2) at non-singleton dimension 1

In [ ]:
(torch.abs(p1[0] - rv[0]) + torch.abs(p1[1] - rv[1]))

In [14]:
torch.tensor(3*[0.345])

tensor([0.3450, 0.3450, 0.3450])

In [15]:
x = torch.Tensor([1,2,2,1,3,2,3,1,1,1,2,3,2,2,3,3,3])

In [16]:
(x == 1) * 1

tensor([1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0])

In [18]:
(x == 1) * 1 + (x == 2)*1

tensor([1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0])